/**
 * Participant-facing preview strings (SPEC-0007/FR-006, NFR-001).
 *
 * English is what a participant sees by default; German is kept alongside it so the
 * strings stay extractable and a locale switch is a wiring change, not a rewrite of the
 * components. No string belonging to the preview lives inline in a component.
 */
export type PreviewLocale = 'en' | 'de'

export type PreviewMessages = {
  testTab: string
  traceTab: string
  questionHeading: string
  questionMissing: string
  answerLabel: string
  answerPlaceholder: string
  submit: string
  submitting: string
  runHint: string
  resultsHeading: string
  resultsEmpty: string
  passed: string
  classificationsHeading: string
  aiDisclaimer: string
  answerTooShort: (minChars: number) => string
  answerTooLong: (maxChars: number) => string
  answerBoundsConflict: (minChars: number, maxChars: number) => string
}

const en: PreviewMessages = {
  testTab: 'Test',
  traceTab: 'Trace',
  questionHeading: 'Question',
  questionMissing: 'This workflow has no question node yet.',
  answerLabel: 'Your answer',
  answerPlaceholder: 'Write the answer you want to test…',
  submit: 'Run assessment',
  submitting: 'Assessing…',
  runHint: 'An assessment can take up to two minutes. Do not reload the page.',
  resultsHeading: 'Results',
  resultsEmpty: 'Run the workflow to see the score, classification and feedback.',
  passed: 'Passed',
  classificationsHeading: 'Classification',
  aiDisclaimer: 'Generated by a language model, so it can be wrong or misleading.',
  answerTooShort: (minChars) => `This workflow asks for at least ${minChars} characters.`,
  answerTooLong: (maxChars) => `This workflow allows at most ${maxChars} characters.`,
  answerBoundsConflict: (minChars, maxChars) =>
    `This workflow asks for at least ${minChars} characters but allows at most ${maxChars}. Fix the answer node before running.`
}

const de: PreviewMessages = {
  testTab: 'Test',
  traceTab: 'Verlauf',
  questionHeading: 'Aufgabe',
  questionMissing: 'Dieser Workflow hat noch keinen Frage-Knoten.',
  answerLabel: 'Deine Antwort',
  answerPlaceholder: 'Schreibe hier die Antwort, die du testen möchtest…',
  submit: 'Bewertung starten',
  submitting: 'Wird ausgewertet…',
  runHint:
    'Die Auswertung kann bis zu zwei Minuten dauern. Bitte die Seite nicht neu laden.',
  resultsHeading: 'Ergebnisse',
  resultsEmpty: 'Starte den Workflow, um Punktzahl, Einordnung und Feedback zu sehen.',
  passed: 'Bestanden',
  classificationsHeading: 'Einordnung',
  aiDisclaimer:
    'Von einem Sprachmodell erzeugt und daher möglicherweise falsch oder irreführend.',
  answerTooShort: (minChars) =>
    `Dieser Workflow verlangt mindestens ${minChars} Zeichen.`,
  answerTooLong: (maxChars) => `Dieser Workflow erlaubt höchstens ${maxChars} Zeichen.`,
  answerBoundsConflict: (minChars, maxChars) =>
    `Dieser Workflow verlangt mindestens ${minChars} Zeichen, erlaubt aber höchstens ${maxChars}. Bitte den Antwort-Knoten korrigieren.`
}

export const DEFAULT_PREVIEW_LOCALE: PreviewLocale = 'en'

export const previewMessages: Record<PreviewLocale, PreviewMessages> = { en, de }
