/**
 * Participant-facing preview strings (SPEC-0007/FR-006, NFR-001).
 *
 * English is what a participant sees by default; German is kept alongside it so the
 * strings stay extractable and a locale switch is a wiring change, not a rewrite of the
 * components. No string belonging to the preview lives inline in a component.
 */
export type PreviewLocale = 'en' | 'de'

export type PreviewMessages = {
  testTab: string
  traceTab: string
  questionHeading: string
  questionMissing: string
  answerLabel: string
  answerPlaceholder: string
  submit: string
  submitting: string
  runHint: string
  runFailed: string
  runCancelled: string
  runDisconnected: string
  retry: string
  viewTrace: string
  waitingToStart: string
  assessingProgress: (pct: number) => string
  resultsHeading: string
  resultsEmpty: string
  passed: string
  classificationsHeading: string
  aiDisclaimer: string
  /** Review output chips and caption (SPEC-0020/FR-002). */
  needsReview: string
  noIssueFound: string
  reviewNoReason: string
  reviewCaption: string
  /** Editor-only affordance on a result card: jump to the node that produced it. */
  locateOutputNode: (label: string) => string
  answerTooShort: (minChars: number) => string
  answerTooLong: (maxChars: number) => string
  answerBoundsConflict: (minChars: number, maxChars: number) => string
  /** The Submissions inbox (SPEC-0020/FR-009 to FR-012). */
  submissionsTab: (needsReview: number) => string
  submissionsTotal: string
  reviewed: string
  failed: string
  submissionCounts: string
  filterSubmissions: string
  filterAll: string
  submissionList: string
  submissionDetail: string
  submissionsEmpty: string
  submissionsFilterEmpty: string
  submissionsLoadFailed: string
  submissionGone: string
  showingLatest: (count: number) => string
  emptyAnswer: string
  scoreChip: (score: number) => string
  runDuration: (ms: number) => string
  back: string
  answerHeading: string
  noOutputs: string
  flagReason: string
  tutorReview: string
  reviewNoteLabel: string
  markReviewed: string
  reopenReview: string
  reviewedAt: (when: string) => string
  reviewSaveFailed: string
  runAgain: string
  runAgainHint: string
  submittedBy: (name: string) => string
}

const durationLabel = (ms: number, secondsUnit: string): string =>
  ms < 1000 ? `${ms} ms` : `${(ms / 1000).toFixed(1)} ${secondsUnit}`

const en: PreviewMessages = {
  testTab: 'Test',
  traceTab: 'Trace',
  questionHeading: 'Question',
  questionMissing: 'This workflow has no question node yet.',
  answerLabel: 'Your answer',
  answerPlaceholder: 'Write the answer you want to test…',
  submit: 'Run assessment',
  submitting: 'Assessing…',
  runHint: 'An assessment can take up to two minutes. Do not reload the page.',
  runFailed: 'The run failed.',
  runCancelled: 'The run was cancelled.',
  runDisconnected:
    'Connection to the server is unavailable. Check your connection and retry.',
  retry: 'Retry',
  viewTrace: 'View trace',
  waitingToStart: 'Waiting to start…',
  assessingProgress: (pct) => `Assessing… ${pct}%`,
  resultsHeading: 'Results',
  resultsEmpty: 'Run the workflow to see the score, classification and feedback.',
  passed: 'Passed',
  classificationsHeading: 'Classification',
  aiDisclaimer: 'Generated by a language model, so it can be wrong or misleading.',
  needsReview: 'Needs review',
  noIssueFound: 'No issue found',
  reviewNoReason: 'Flagged without a reason.',
  reviewCaption: 'A recommendation, not an approval.',
  locateOutputNode: (label) => `Locate ${label} on the canvas`,
  answerTooShort: (minChars) => `This workflow asks for at least ${minChars} characters.`,
  answerTooLong: (maxChars) => `This workflow allows at most ${maxChars} characters.`,
  answerBoundsConflict: (minChars, maxChars) =>
    `This workflow asks for at least ${minChars} characters but allows at most ${maxChars}. Fix the answer node before running.`,
  submissionsTab: (needsReview) =>
    needsReview > 0 ? `Submissions (${needsReview})` : 'Submissions',
  submissionsTotal: 'Submissions',
  reviewed: 'Reviewed',
  failed: 'Failed',
  submissionCounts: 'Submission counts',
  filterSubmissions: 'Filter submissions',
  filterAll: 'All',
  submissionList: 'Submission list',
  submissionDetail: 'Submission',
  submissionsEmpty: 'No submissions yet. Run an answer to see it here as a tutor would.',
  submissionsFilterEmpty: 'No submissions match this filter.',
  submissionsLoadFailed: 'Submissions could not be loaded.',
  submissionGone: 'This submission no longer exists.',
  showingLatest: (count) => `Showing the latest ${count} submissions.`,
  emptyAnswer: 'Empty answer',
  scoreChip: (score) => `Score ${score}`,
  runDuration: (ms) => durationLabel(ms, 's'),
  back: 'Back to submissions',
  answerHeading: 'Answer',
  noOutputs: 'This run produced no outputs.',
  flagReason: 'Why it was flagged',
  tutorReview: 'Tutor review',
  reviewNoteLabel: 'Note (optional)',
  markReviewed: 'Mark as reviewed',
  reopenReview: 'Reopen',
  reviewedAt: (when) => `Reviewed ${when}`,
  reviewSaveFailed: 'The review could not be saved.',
  runAgain: 'Run again',
  runAgainHint: 'Runs this answer against the current graph.',
  submittedBy: (name) => `Submitted by ${name}`
}

const de: PreviewMessages = {
  testTab: 'Test',
  traceTab: 'Verlauf',
  questionHeading: 'Aufgabe',
  questionMissing: 'Dieser Workflow hat noch keinen Frage-Knoten.',
  answerLabel: 'Deine Antwort',
  answerPlaceholder: 'Schreibe hier die Antwort, die du testen möchtest…',
  submit: 'Bewertung starten',
  submitting: 'Wird ausgewertet…',
  runHint:
    'Die Auswertung kann bis zu zwei Minuten dauern. Bitte die Seite nicht neu laden.',
  runFailed: 'Die Auswertung ist fehlgeschlagen.',
  runCancelled: 'Die Auswertung wurde abgebrochen.',
  runDisconnected:
    'Keine Verbindung zum Server. Bitte Verbindung prüfen und erneut versuchen.',
  retry: 'Erneut versuchen',
  viewTrace: 'Verlauf ansehen',
  waitingToStart: 'Warte auf Start…',
  assessingProgress: (pct) => `Wird ausgewertet… ${pct}%`,
  resultsHeading: 'Ergebnisse',
  resultsEmpty: 'Starte den Workflow, um Punktzahl, Einordnung und Feedback zu sehen.',
  passed: 'Bestanden',
  classificationsHeading: 'Einordnung',
  aiDisclaimer:
    'Von einem Sprachmodell erzeugt und daher möglicherweise falsch oder irreführend.',
  needsReview: 'Prüfung nötig',
  noIssueFound: 'Kein Befund',
  reviewNoReason: 'Ohne Begründung markiert.',
  reviewCaption: 'Eine Empfehlung, keine Freigabe.',
  locateOutputNode: (label) => `${label} auf der Zeichenfläche anzeigen`,
  answerTooShort: (minChars) =>
    `Dieser Workflow verlangt mindestens ${minChars} Zeichen.`,
  answerTooLong: (maxChars) => `Dieser Workflow erlaubt höchstens ${maxChars} Zeichen.`,
  answerBoundsConflict: (minChars, maxChars) =>
    `Dieser Workflow verlangt mindestens ${minChars} Zeichen, erlaubt aber höchstens ${maxChars}. Bitte den Antwort-Knoten korrigieren.`,
  submissionsTab: (needsReview) =>
    needsReview > 0 ? `Einreichungen (${needsReview})` : 'Einreichungen',
  submissionsTotal: 'Einreichungen',
  reviewed: 'Geprüft',
  failed: 'Fehlgeschlagen',
  submissionCounts: 'Anzahl der Einreichungen',
  filterSubmissions: 'Einreichungen filtern',
  filterAll: 'Alle',
  submissionList: 'Liste der Einreichungen',
  submissionDetail: 'Einreichung',
  submissionsEmpty:
    'Noch keine Einreichungen. Starte eine Antwort, um sie hier aus Tutor-Sicht zu sehen.',
  submissionsFilterEmpty: 'Keine Einreichungen für diesen Filter.',
  submissionsLoadFailed: 'Die Einreichungen konnten nicht geladen werden.',
  submissionGone: 'Diese Einreichung existiert nicht mehr.',
  showingLatest: (count) => `Die neuesten ${count} Einreichungen werden angezeigt.`,
  emptyAnswer: 'Leere Antwort',
  scoreChip: (score) => `Punktzahl ${score}`,
  runDuration: (ms) => durationLabel(ms, 's'),
  back: 'Zurück zu den Einreichungen',
  answerHeading: 'Antwort',
  noOutputs: 'Diese Auswertung hat keine Ausgaben erzeugt.',
  flagReason: 'Grund für die Markierung',
  tutorReview: 'Prüfung durch die Lehrperson',
  reviewNoteLabel: 'Notiz (optional)',
  markReviewed: 'Als geprüft markieren',
  reopenReview: 'Erneut öffnen',
  reviewedAt: (when) => `Geprüft ${when}`,
  reviewSaveFailed: 'Die Prüfung konnte nicht gespeichert werden.',
  runAgain: 'Erneut ausführen',
  runAgainHint: 'Führt diese Antwort mit dem aktuellen Graphen aus.',
  submittedBy: (name) => `Eingereicht von ${name}`
}

export const DEFAULT_PREVIEW_LOCALE: PreviewLocale = 'en'

export const previewMessages: Record<PreviewLocale, PreviewMessages> = { en, de }
