-- SPEC-0022: a workshop offers several workflow templates, each pinned to a revision or
-- following the template's current revision. Existing workshops keep their single pinned
-- revision as entry 0. The legacy Workshop columns become optional and are no longer used;
-- a later migration drops them (additive while LegacyGraph exists).

-- CreateTable
CREATE TABLE "WorkshopTemplate" (
    "id" TEXT NOT NULL,
    "workshopId" TEXT NOT NULL,
    "templateId" TEXT NOT NULL,
    "templateRevisionId" TEXT,
    "position" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WorkshopTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "WorkshopTemplate_workshopId_templateId_key" ON "WorkshopTemplate"("workshopId", "templateId");

-- CreateIndex
CREATE INDEX "WorkshopTemplate_workshopId_position_idx" ON "WorkshopTemplate"("workshopId", "position");

-- CreateIndex
CREATE INDEX "WorkshopTemplate_templateId_idx" ON "WorkshopTemplate"("templateId");

-- CreateIndex
CREATE INDEX "WorkshopTemplate_templateRevisionId_idx" ON "WorkshopTemplate"("templateRevisionId");

-- AddForeignKey
ALTER TABLE "WorkshopTemplate" ADD CONSTRAINT "WorkshopTemplate_workshopId_fkey" FOREIGN KEY ("workshopId") REFERENCES "Workshop"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WorkshopTemplate" ADD CONSTRAINT "WorkshopTemplate_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "Template"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WorkshopTemplate" ADD CONSTRAINT "WorkshopTemplate_templateRevisionId_fkey" FOREIGN KEY ("templateRevisionId") REFERENCES "TemplateRevision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Backfill: every existing workshop keeps its pinned revision as its only entry. The id is
-- built here because cuid() is generated by the client, not the database.
INSERT INTO "WorkshopTemplate" ("id", "workshopId", "templateId", "templateRevisionId", "position", "createdAt")
SELECT 'wt' || w."id", w."id", w."templateId", w."templateRevisionId", 0, w."createdAt"
FROM "Workshop" w
WHERE w."templateId" IS NOT NULL
ON CONFLICT DO NOTHING;

-- AlterTable
ALTER TABLE "Workshop" ALTER COLUMN "templateId" DROP NOT NULL,
ALTER COLUMN "templateRevisionId" DROP NOT NULL;
