import {
  KATALYST_MODEL_QWEN_FLASH,
  PROVIDER_KEY_KATALYST,
} from '@haski/ta-lib';
import type { BundledTemplate } from './bundled-template.js';

type SerializedInput = { name: string; type: string; link: number | null };
type SerializedOutput = { name: string; type: string; links: number[] };

const input = (
  name: string,
  type: string,
  link: number | null,
): SerializedInput => ({ name, type, link });

const output = (
  name: string,
  type: string,
  links: number[] = [],
): SerializedOutput => ({ name, type, links });

const node = ({
  id,
  type,
  pos,
  title,
  inputs = [],
  outputs = [],
  properties = {},
  widgetsValues,
  size = [260, 100],
}: {
  id: number;
  type: string;
  pos: [number, number];
  title: string;
  inputs?: SerializedInput[];
  outputs?: SerializedOutput[];
  properties?: Record<string, unknown>;
  widgetsValues?: unknown[];
  size?: [number, number];
}) => ({
  id,
  type,
  pos,
  size,
  flags: {},
  order: id - 1,
  mode: 0,
  inputs,
  outputs,
  title,
  properties,
  ...(widgetsValues ? { widgets_values: widgetsValues } : {}),
});

const llmProperties = {
  value: KATALYST_MODEL_QWEN_FLASH,
  model: KATALYST_MODEL_QWEN_FLASH,
  model_ref: {
    providerKey: PROVIDER_KEY_KATALYST,
    modelId: KATALYST_MODEL_QWEN_FLASH,
  },
  needs_model_selection: false,
  max_tokens: 2048,
  temperature: 0.2,
  top_p: 0.9,
  top_k: 40,
  presence_penalty: 0,
};

const systemPrompt = [
  '/no_think',
  'You are a concise software-design assessor.',
  'Use the supplied rubric, learner answer, and deterministic diagnostics.',
  'Begin with exactly: Score: <integer from 0 to 100>.',
  'Then give three short sentences covering strengths, gaps, and one next step.',
  'Treat the deterministic diagnostics as evidence and resolve contradictions explicitly.',
].join('\n');

const rubricDocument = [
  'Strategy pattern rubric (100 points)',
  '30: identifies a family of interchangeable algorithms.',
  '25: explains the context delegates behavior to a strategy.',
  '20: explains runtime selection or replacement.',
  '15: gives a concrete example with at least two strategies.',
  '10: discusses one trade-off such as added classes or indirection.',
].join('\n');

/**
 * A workshop-sized integration graph that exercises every registered node type.
 * Its primary path produces model feedback and a blended score. Parallel branches
 * expose lexical, semantic, length, and TF-IDF diagnostics for node verification.
 */
export const extendedAssessmentLabTemplate: BundledTemplate = {
  slug: 'extended-assessment-lab',
  kind: 'WORKFLOW',
  name: 'Extended assessment laboratory',
  description:
    'A complete strategy-pattern assessment using the KATALYST model plus the full node palette.',
  category: 'Assessment laboratories',
  tags: ['assessment', 'llm', 'katalyst', 'validation', 'extended-palette'],
  content: {
    last_node_id: 44,
    last_link_id: 47,
    nodes: [
      node({
        id: 1,
        type: 'input/question',
        pos: [40, 80],
        title: 'Assessment question',
        outputs: [output('string', 'string', [1])],
        properties: {
          value:
            'Explain the Strategy design pattern, give a concrete example with two interchangeable strategies, and discuss one trade-off.',
        },
        size: [320, 130],
      }),
      node({
        id: 2,
        type: 'input/answer',
        pos: [40, 250],
        title: 'Learner answer',
        outputs: [output('string', 'string', [2])],
        properties: { value: '', minChars: 80, maxChars: 1200 },
        size: [320, 100],
      }),
      node({
        id: 3,
        type: 'input/sample-solution',
        pos: [40, 400],
        title: 'Reference solution',
        outputs: [output('string', 'string', [5, 6])],
        properties: {
          value:
            'The Strategy pattern defines interchangeable algorithms behind a common interface. A context delegates work to its current strategy and can replace it at runtime. A route planner can switch between car and bicycle routing strategies. This flexibility adds classes and indirection.',
        },
        size: [320, 180],
      }),
      node({
        id: 4,
        type: 'basic/textfield',
        pos: [40, 630],
        title: 'Required concepts',
        outputs: [output('string', 'string', [7])],
        properties: {
          precision: 1,
          value: 'strategy, context, interchangeable, runtime, algorithm',
        },
        size: [320, 120],
      }),
      node({
        id: 5,
        type: 'basic/document-loader',
        pos: [40, 800],
        title: 'Rubric document',
        outputs: [output('string', 'string', [8])],
        properties: {
          value: rubricDocument,
          documentName: 'strategy-pattern-rubric.md',
        },
        size: [320, 140],
      }),
      node({
        id: 6,
        type: 'basic/number',
        pos: [40, 1010],
        title: 'Answer character limit',
        outputs: [output('number', 'number', [9])],
        properties: { value: 1200 },
        widgetsValues: [1200],
      }),
      node({
        id: 7,
        type: 'basic/number',
        pos: [40, 1150],
        title: 'Similarity scale',
        outputs: [output('number', 'number', [10])],
        properties: { value: 100 },
        widgetsValues: [100],
      }),
      node({
        id: 8,
        type: 'basic/number',
        pos: [40, 1290],
        title: 'Length diagnostic offset',
        outputs: [output('number', 'number', [11])],
        properties: { value: 5 },
        widgetsValues: [5],
      }),
      node({
        id: 9,
        type: 'basic/number',
        pos: [40, 1430],
        title: 'Score average divisor',
        outputs: [output('number', 'number', [12])],
        properties: { value: 2 },
        widgetsValues: [2],
      }),
      node({
        id: 10,
        type: 'basic/Image',
        pos: [40, 1580],
        title: 'Strategy pattern visual cue',
        outputs: [output('*', '*')],
        properties: {
          imageUrl:
            'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="320" height="120"%3E%3Crect width="320" height="120" rx="12" fill="%23272727"/%3E%3Ctext x="160" y="34" fill="%23fff" text-anchor="middle" font-family="sans-serif" font-size="16"%3EContext%3C/text%3E%3Cpath d="M160 43V72M80 72H240M80 72V92M240 72V92" stroke="%239bbcff" stroke-width="3"/%3E%3Ctext x="80" y="111" fill="%23fff" text-anchor="middle" font-family="sans-serif" font-size="13"%3EStrategy A%3C/text%3E%3Ctext x="240" y="111" fill="%23fff" text-anchor="middle" font-family="sans-serif" font-size="13"%3EStrategy B%3C/text%3E%3C/svg%3E',
        },
        size: [320, 180],
      }),
      node({
        id: 11,
        type: 'preprocessing/clean',
        pos: [430, 250],
        title: 'Normalize learner answer',
        inputs: [input('string', 'string', 2)],
        outputs: [output('string', 'string', [13, 14, 15, 16])],
        properties: {
          value: '',
          trim: true,
          space: false,
          doubleSpace: true,
          dot: false,
          comma: false,
          lower: false,
          upper: false,
          stem: false,
          removeEnclosingSpecialChars: true,
        },
        widgetsValues: [
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
        ],
      }),
      node({
        id: 12,
        type: 'utils/route',
        pos: [750, 250],
        title: 'Route normalized answer',
        inputs: [input('*', '*', 13)],
        outputs: [output('*', '*', [17, 18, 19])],
        properties: { value: '' },
      }),
      node({
        id: 13,
        type: 'basic/watch',
        pos: [1030, 190],
        title: 'Inspect normalized answer',
        inputs: [input('*', '*', 17)],
        properties: { value: '' },
        size: [220, 80],
      }),
      node({
        id: 14,
        type: 'text/keyword-check',
        pos: [1030, 340],
        title: 'Required concept coverage',
        inputs: [
          input('keywords (comma-separated)', 'string', 7),
          input('text', 'string', 19),
        ],
        outputs: [
          output('present keywords', 'string', [20]),
          output('missing keywords', 'string', [21]),
        ],
        properties: {
          useSemantic: false,
          presentKeywords: '',
          missingKeywords: '',
        },
        widgetsValues: [false],
        size: [280, 110],
      }),
      node({
        id: 15,
        type: 'utils/strings-to-array',
        pos: [1370, 340],
        title: 'Collect concept diagnostics',
        inputs: [input('string', 'string', 20), input('string', 'string', 21)],
        outputs: [output('[string]', '[string]', [22])],
        properties: { value: [] },
      }),
      node({
        id: 16,
        type: 'utils/string-array-to-string',
        pos: [1690, 340],
        title: 'Format concept diagnostics',
        inputs: [input('[string]', '[string]', 22)],
        outputs: [output('string', 'string', [23, 46])],
        properties: { value: '', separator: ' | ' },
        widgetsValues: [' | '],
      }),
      node({
        id: 17,
        type: 'utils/count',
        pos: [750, 510],
        title: 'Count answer words',
        inputs: [input('string', 'string', 14)],
        outputs: [output('number', 'number', [24])],
        properties: { operation: 'words' },
        widgetsValues: ['words'],
      }),
      node({
        id: 18,
        type: 'basic/tf-idf',
        pos: [750, 680],
        title: 'TF-IDF answer terms',
        inputs: [input('string', 'string', 5), input('string', 'string', 15)],
        outputs: [output('*', '*', [25])],
        properties: {},
        size: [260, 120],
      }),
      node({
        id: 19,
        type: 'models/sentence-transformer',
        pos: [430, 920],
        title: 'Embed reference solution',
        inputs: [input('string', 'string', 6)],
        outputs: [output('[number]', '[number]', [26])],
        properties: { value: -1 },
      }),
      node({
        id: 20,
        type: 'models/sentence-transformer',
        pos: [750, 920],
        title: 'Embed learner answer',
        inputs: [input('string', 'string', 16)],
        outputs: [output('[number]', '[number]', [27])],
        properties: { value: -1 },
      }),
      node({
        id: 21,
        type: 'models/cosine-similarity',
        pos: [1070, 920],
        title: 'Semantic similarity',
        inputs: [
          input('[number]', '[number]', 26),
          input('[number]', '[number]', 27),
        ],
        outputs: [output('number', 'number', [28])],
        properties: { value: -1 },
      }),
      node({
        id: 22,
        type: 'math/math-operation',
        pos: [1390, 920],
        title: 'Similarity percentage',
        inputs: [input('number', 'number', 28), input('number', 'number', 10)],
        outputs: [output('number', 'number', [29])],
        properties: { operation: '*', valueOne: 0, valueTwo: 100 },
        widgetsValues: ['*'],
      }),
      node({
        id: 23,
        type: 'math/precision',
        pos: [1710, 920],
        title: 'Rounded semantic score',
        inputs: [input('number', 'number', 29)],
        outputs: [output('number', 'number', [30, 47])],
        properties: { value: -1, precision: 1 },
        widgetsValues: [1],
      }),
      node({
        id: 24,
        type: 'input/max-input-chars',
        pos: [430, 1110],
        title: 'Apply answer character limit',
        inputs: [input('number', 'number', 9)],
        properties: { value: 1200 },
      }),
      node({
        id: 25,
        type: 'utils/concat-string',
        pos: [430, 80],
        title: 'Question and normalized answer',
        inputs: [input('string', 'string', 1), input('string', 'string', 18)],
        outputs: [output('string', 'string', [31])],
        properties: { value: '', space: true },
        widgetsValues: [true],
      }),
      node({
        id: 26,
        type: 'utils/concat-string',
        pos: [750, 80],
        title: 'Rubric and response context',
        inputs: [input('string', 'string', 8), input('string', 'string', 31)],
        outputs: [output('string', 'string', [32])],
        properties: { value: '', space: true },
        widgetsValues: [true],
      }),
      node({
        id: 27,
        type: 'utils/concat-string',
        pos: [1070, 80],
        title: 'Append deterministic evidence',
        inputs: [input('string', 'string', 32), input('string', 'string', 23)],
        outputs: [output('string', 'string', [33])],
        properties: { value: '', space: true },
        widgetsValues: [true],
      }),
      node({
        id: 28,
        type: 'basic/textfield',
        pos: [1070, 570],
        title: 'Assessment instructions',
        outputs: [output('string', 'string', [34])],
        properties: { precision: 1, value: systemPrompt },
        size: [300, 190],
      }),
      node({
        id: 29,
        type: 'basic/prompt-message',
        pos: [1430, 570],
        title: 'System assessment message',
        inputs: [input('string', 'string', 34)],
        outputs: [output('message', 'message', [35])],
        properties: { value: { role: 'system', content: '' } },
        widgetsValues: ['system'],
      }),
      node({
        id: 30,
        type: 'basic/prompt-message',
        pos: [1430, 80],
        title: 'Learner evidence message',
        inputs: [input('string', 'string', 33)],
        outputs: [output('message', 'message', [36])],
        properties: { value: { role: 'user', content: '' } },
        widgetsValues: ['user'],
      }),
      node({
        id: 31,
        type: 'utils/concat-object',
        pos: [1770, 220],
        title: 'Assessment messages',
        inputs: [input('*', '*', 35), input('*', '*', 36)],
        outputs: [output('*', '*', [37])],
        properties: { value: [] },
      }),
      node({
        id: 32,
        type: 'models/llm',
        pos: [2090, 180],
        title: 'KATALYST assessment model',
        inputs: [input('message', 'message', null), input('messages', '*', 37)],
        outputs: [output('string', 'string', [38, 39, 40])],
        properties: llmProperties,
        widgetsValues: [2048, 0.2, 0.9, 40, 0, KATALYST_MODEL_QWEN_FLASH],
        size: [320, 220],
      }),
      node({
        id: 33,
        type: 'preprocessing/extract-number',
        pos: [2470, 180],
        title: 'Extract model score',
        inputs: [input('string', 'string', 38)],
        outputs: [output('number', 'number', [41])],
        properties: { value: '' },
      }),
      node({
        id: 34,
        type: 'basic/sum',
        pos: [2790, 350],
        title: 'Combine model and semantic scores',
        inputs: [input('A', 'number', 41), input('B', 'number', 30)],
        outputs: [output('A+B', 'number', [42])],
        properties: { precision: 1, path: 'basic/sum' },
      }),
      node({
        id: 35,
        type: 'math/math-operation',
        pos: [3110, 350],
        title: 'Average composite score',
        inputs: [input('number', 'number', 42), input('number', 'number', 12)],
        outputs: [output('number', 'number', [43])],
        properties: { operation: '/', valueOne: 0, valueTwo: 2 },
        widgetsValues: ['/'],
      }),
      node({
        id: 36,
        type: 'math/precision',
        pos: [3430, 350],
        title: 'Final rounded score',
        inputs: [input('number', 'number', 43)],
        outputs: [output('number', 'number', [44])],
        properties: { value: -1, precision: 1 },
        widgetsValues: [1],
      }),
      node({
        id: 37,
        type: 'basic/sum',
        pos: [1070, 1100],
        title: 'Length diagnostic',
        inputs: [input('A', 'number', 24), input('B', 'number', 11)],
        outputs: [output('A+B', 'number', [45])],
        properties: { precision: 1, path: 'basic/sum' },
      }),
      node({
        id: 38,
        type: 'output/output',
        pos: [2790, 80],
        title: 'Feedback output',
        inputs: [input('*', '*', 39)],
        properties: {
          uniqueId: '38',
          type: 'text',
          label: 'Model feedback',
          value: '',
        },
        widgetsValues: ['Model feedback', 'text'],
      }),
      node({
        id: 39,
        type: 'output/output',
        pos: [3750, 350],
        title: 'Composite score output',
        inputs: [input('*', '*', 44)],
        properties: {
          uniqueId: '39',
          type: 'score',
          label: 'Composite score',
          value: '',
        },
        widgetsValues: ['Composite score', 'score'],
      }),
      node({
        id: 40,
        type: 'output/output',
        pos: [2030, 500],
        title: 'Concept diagnostics output',
        inputs: [input('*', '*', 46)],
        properties: {
          uniqueId: '40',
          type: 'text',
          label: 'Present | missing concepts',
          value: '',
        },
        widgetsValues: ['Present | missing concepts', 'text'],
      }),
      node({
        id: 41,
        type: 'output/output',
        pos: [2030, 920],
        title: 'Semantic score output',
        inputs: [input('*', '*', 47)],
        properties: {
          uniqueId: '41',
          type: 'score',
          label: 'Semantic similarity',
          value: '',
        },
        widgetsValues: ['Semantic similarity', 'score'],
      }),
      node({
        id: 42,
        type: 'output/output',
        pos: [1390, 1100],
        title: 'Length output',
        inputs: [input('*', '*', 45)],
        properties: {
          uniqueId: '42',
          type: 'text',
          label: 'Word count + 5',
          value: '',
        },
        widgetsValues: ['Word count + 5', 'text'],
      }),
      node({
        id: 43,
        type: 'output/output',
        pos: [1070, 680],
        title: 'TF-IDF output',
        inputs: [input('*', '*', 25)],
        properties: {
          uniqueId: '43',
          type: 'text',
          label: 'TF-IDF diagnostics',
          value: '',
        },
        widgetsValues: ['TF-IDF diagnostics', 'text'],
      }),
      node({
        id: 44,
        type: 'basic/watch',
        pos: [2470, 300],
        title: 'Inspect model response',
        inputs: [input('*', '*', 40)],
        properties: { value: '' },
        size: [240, 80],
      }),
    ],
    links: [
      [1, 1, 0, 25, 0, 'string'],
      [2, 2, 0, 11, 0, 'string'],
      [5, 3, 0, 18, 0, 'string'],
      [6, 3, 0, 19, 0, 'string'],
      [7, 4, 0, 14, 0, 'string'],
      [8, 5, 0, 26, 0, 'string'],
      [9, 6, 0, 24, 0, 'number'],
      [10, 7, 0, 22, 1, 'number'],
      [11, 8, 0, 37, 1, 'number'],
      [12, 9, 0, 35, 1, 'number'],
      [13, 11, 0, 12, 0, 'string'],
      [14, 11, 0, 17, 0, 'string'],
      [15, 11, 0, 18, 1, 'string'],
      [16, 11, 0, 20, 0, 'string'],
      [17, 12, 0, 13, 0, '*'],
      [18, 12, 0, 25, 1, '*'],
      [19, 12, 0, 14, 1, '*'],
      [20, 14, 0, 15, 0, 'string'],
      [21, 14, 1, 15, 1, 'string'],
      [22, 15, 0, 16, 0, '[string]'],
      [23, 16, 0, 27, 1, 'string'],
      [24, 17, 0, 37, 0, 'number'],
      [25, 18, 0, 43, 0, '*'],
      [26, 19, 0, 21, 0, '[number]'],
      [27, 20, 0, 21, 1, '[number]'],
      [28, 21, 0, 22, 0, 'number'],
      [29, 22, 0, 23, 0, 'number'],
      [30, 23, 0, 34, 1, 'number'],
      [31, 25, 0, 26, 1, 'string'],
      [32, 26, 0, 27, 0, 'string'],
      [33, 27, 0, 30, 0, 'string'],
      [34, 28, 0, 29, 0, 'string'],
      [35, 29, 0, 31, 0, 'message'],
      [36, 30, 0, 31, 1, 'message'],
      [37, 31, 0, 32, 1, '*'],
      [38, 32, 0, 33, 0, 'string'],
      [39, 32, 0, 38, 0, 'string'],
      [40, 32, 0, 44, 0, 'string'],
      [41, 33, 0, 34, 0, 'number'],
      [42, 34, 0, 35, 0, 'number'],
      [43, 35, 0, 36, 0, 'number'],
      [44, 36, 0, 39, 0, 'number'],
      [45, 37, 0, 42, 0, 'number'],
      [46, 16, 0, 40, 0, 'string'],
      [47, 23, 0, 41, 0, 'number'],
    ],
    groups: [
      {
        title: 'Inputs and reference material',
        bounding: [10, 30, 370, 1760],
        color: '#50664a',
        font_size: 24,
      },
      {
        title: 'Deterministic validation',
        bounding: [400, 210, 1580, 1110],
        color: '#6f621f',
        font_size: 24,
      },
      {
        title: 'KATALYST assessment',
        bounding: [400, 30, 3400, 780],
        color: '#405775',
        font_size: 24,
      },
    ],
    config: {},
    extra: {},
    version: 0.4,
  },
};
