import { PROVIDER_KEY_OPENROUTER } from '@haski/ta-lib';
import type { BundledTemplate } from './bundled-template.js';

const RUBRIC = [
  'You grade short free-text answers for a teacher.',
  '',
  'Rubric (100 points):',
  '- 40 points: names light, water and carbon dioxide as the inputs.',
  '- 40 points: names glucose (sugar) and oxygen as the outputs.',
  '- 20 points: explains why the process matters for other organisms.',
  '',
  'Grade the answer against the rubric. Justify the grade in two sentences and',
  'end your reply with a single line in the form: Score: <number between 0 and 100>',
].join('\n');

const CLASSIFICATION = [
  'Read the assessment below and classify the answer.',
  'Reply with exactly one of these labels and nothing else:',
  'correct, partially correct, incorrect.',
].join('\n');

const FEEDBACK = [
  'You write feedback for the student whose answer was just assessed.',
  'Write at most three sentences: what the answer got right, what is missing,',
  'and one concrete next step. Address the student directly.',
].join('\n');

const llmProperties = (maxTokens: number) => ({
  value: 'openrouter/free',
  model: 'openrouter/free',
  model_ref: {
    providerKey: PROVIDER_KEY_OPENROUTER,
    modelId: 'openrouter/free',
  },
  needs_model_selection: false,
  max_tokens: maxTokens,
  temperature: 0.2,
  top_p: 1,
  top_k: 50,
  presence_penalty: 0,
});

/**
 * The canonical WAIE free-text assessment workflow (SPEC-0007/FR-001).
 *
 * Input (question, answer) feeds an Assessment stage (rubric, rubric prompt, model,
 * extracted score), whose reply feeds Classification, and both feed Feedback. The three
 * stages are separate prompts on purpose: the workshop assignment is to change a rubric,
 * swap a feedback strategy or insert a validation step, and that is only editable if each
 * stage has its own prompt node rather than one monolithic prompt.
 *
 * Each stage wires its text straight into the model's `messages` slot, which takes a
 * plain string since SPEC-0019/FR-002; only the stage instructions still pass through a
 * `prompt-message`, because that node is what carries the `system` role (FR-004). The
 * `concat-object` that used to merge the two message objects is gone — the model
 * composes system-then-user from its two ports (FR-009).
 *
 * Every model node starts on OpenRouter's free-model router. The facilitator controls
 * access server-side through provider credentials and model policy (ADR-0008).
 */
export const waieAssessmentTemplate: BundledTemplate = {
  slug: 'waie-assessment',
  kind: 'WORKFLOW',
  name: 'WAIE free-text assessment',
  description:
    'The canonical workshop workflow: a rubric-based assessment, a classification of the answer, and written feedback.',
  category: 'Workshop',
  tags: ['waie', 'assessment', 'llm'],
  content: {
    last_node_id: 24,
    last_link_id: 24,
    nodes: [
      {
        id: 1,
        type: 'input/question',
        pos: [40, 60],
        size: [280, 120],
        flags: {},
        order: 0,
        mode: 0,
        inputs: [],
        outputs: [{ name: 'string', type: 'string', links: [1] }],
        title: 'Question',
        properties: {
          precision: 1,
          value:
            'Explain why photosynthesis is important for life on Earth. Name the inputs and the outputs of the process.',
        },
      },
      {
        id: 2,
        type: 'input/answer',
        pos: [40, 240],
        size: [280, 80],
        flags: {},
        order: 1,
        mode: 0,
        inputs: [],
        outputs: [{ name: 'string', type: 'string', links: [2] }],
        title: 'Student answer',
        properties: { value: '', minChars: 20, maxChars: 1500 },
      },
      {
        id: 3,
        type: 'basic/textfield',
        pos: [40, 400],
        size: [280, 200],
        flags: {},
        order: 2,
        mode: 0,
        inputs: [],
        outputs: [{ name: 'string', type: 'string', links: [3] }],
        title: 'Rubric',
        properties: { precision: 1, value: RUBRIC },
      },
      {
        id: 4,
        type: 'utils/concat-string',
        pos: [380, 120],
        size: [220, 80],
        flags: {},
        order: 3,
        mode: 0,
        inputs: [
          { name: 'string', type: 'string', link: 1 },
          { name: 'string', type: 'string', link: 2 },
        ],
        outputs: [{ name: 'string', type: 'string', links: [7, 18] }],
        title: 'Question and answer',
        properties: { value: '', space: true },
        widgets_values: [true],
      },
      {
        id: 5,
        type: 'basic/prompt-message',
        pos: [380, 400],
        size: [260, 80],
        flags: {},
        order: 4,
        mode: 0,
        inputs: [{ name: 'string', type: 'string', link: 3 }],
        outputs: [{ name: 'message', type: 'message', links: [5] }],
        title: 'Rubric prompt',
        properties: { value: { role: 'system', content: '' } },
        widgets_values: ['system'],
      },
      {
        id: 8,
        type: 'models/llm',
        pos: [660, 160],
        size: [300, 200],
        flags: {},
        order: 5,
        mode: 0,
        inputs: [
          { name: 'message', type: 'message,string,[message]', link: 5 },
          {
            name: 'messages',
            type: 'message,[message],[string],string',
            link: 7,
          },
        ],
        outputs: [{ name: 'string', type: 'string', links: [8, 14, 19] }],
        title: 'Assessment model',
        properties: llmProperties(256),
      },
      {
        id: 9,
        type: 'preprocessing/extract-number',
        pos: [1020, 160],
        size: [200, 60],
        flags: {},
        order: 6,
        mode: 0,
        inputs: [{ name: 'string', type: 'string', link: 8 }],
        outputs: [{ name: 'number', type: 'number', links: [9] }],
        title: 'Score',
        properties: { value: '' },
      },
      {
        id: 10,
        type: 'output/output',
        pos: [1280, 160],
        size: [210, 80],
        flags: {},
        order: 7,
        mode: 0,
        inputs: [{ name: '*', type: '*', link: 9 }],
        outputs: [],
        title: 'Score output',
        properties: {
          uniqueId: '10',
          type: 'score',
          label: 'Score',
          value: '',
        },
        widgets_values: ['Score', 'score'],
      },
      {
        id: 11,
        type: 'basic/textfield',
        pos: [1220, 460],
        size: [280, 160],
        flags: {},
        order: 8,
        mode: 0,
        inputs: [],
        outputs: [{ name: 'string', type: 'string', links: [10] }],
        title: 'Classification guidance',
        properties: { precision: 1, value: CLASSIFICATION },
      },
      {
        id: 12,
        type: 'basic/prompt-message',
        pos: [1540, 460],
        size: [260, 80],
        flags: {},
        order: 9,
        mode: 0,
        inputs: [{ name: 'string', type: 'string', link: 10 }],
        outputs: [{ name: 'message', type: 'message', links: [12] }],
        title: 'Classification prompt',
        properties: { value: { role: 'system', content: '' } },
        widgets_values: ['system'],
      },
      {
        id: 15,
        type: 'models/llm',
        pos: [1840, 480],
        size: [300, 200],
        flags: {},
        order: 10,
        mode: 0,
        inputs: [
          { name: 'message', type: 'message,string,[message]', link: 12 },
          {
            name: 'messages',
            type: 'message,[message],[string],string',
            link: 14,
          },
        ],
        outputs: [{ name: 'string', type: 'string', links: [15] }],
        title: 'Classification model',
        properties: llmProperties(16),
      },
      {
        id: 16,
        type: 'utils/strings-to-array',
        pos: [2200, 480],
        size: [200, 80],
        flags: {},
        order: 11,
        mode: 0,
        inputs: [
          { name: 'string', type: 'string', link: 15 },
          { name: 'string', type: 'string', link: null },
        ],
        outputs: [{ name: '[string]', type: '[string]', links: [16] }],
        title: 'Classification list',
        properties: { value: [] },
      },
      {
        id: 17,
        type: 'output/output',
        pos: [2460, 480],
        size: [210, 80],
        flags: {},
        order: 12,
        mode: 0,
        inputs: [{ name: '*', type: '*', link: 16 }],
        outputs: [],
        title: 'Classification output',
        properties: {
          uniqueId: '17',
          type: 'classifications',
          label: 'Classification',
          value: '',
        },
        widgets_values: ['Classification', 'classifications'],
      },
      {
        id: 18,
        type: 'basic/textfield',
        pos: [1220, 820],
        size: [280, 160],
        flags: {},
        order: 13,
        mode: 0,
        inputs: [],
        outputs: [{ name: 'string', type: 'string', links: [17] }],
        title: 'Feedback prompt',
        properties: { precision: 1, value: FEEDBACK },
      },
      {
        id: 19,
        type: 'basic/prompt-message',
        pos: [1540, 820],
        size: [260, 80],
        flags: {},
        order: 14,
        mode: 0,
        inputs: [{ name: 'string', type: 'string', link: 17 }],
        outputs: [{ name: 'message', type: 'message', links: [21] }],
        title: 'Feedback instructions',
        properties: { value: { role: 'system', content: '' } },
        widgets_values: ['system'],
      },
      {
        id: 20,
        type: 'utils/concat-string',
        pos: [1540, 960],
        size: [220, 80],
        flags: {},
        order: 15,
        mode: 0,
        inputs: [
          { name: 'string', type: 'string', link: 18 },
          { name: 'string', type: 'string', link: 19 },
        ],
        outputs: [{ name: 'string', type: 'string', links: [23] }],
        title: 'Answer and assessment',
        properties: { value: '', space: true },
        widgets_values: [true],
      },
      {
        id: 23,
        type: 'models/llm',
        pos: [1840, 820],
        size: [300, 200],
        flags: {},
        order: 16,
        mode: 0,
        inputs: [
          { name: 'message', type: 'message,string,[message]', link: 21 },
          {
            name: 'messages',
            type: 'message,[message],[string],string',
            link: 23,
          },
        ],
        outputs: [{ name: 'string', type: 'string', links: [24] }],
        title: 'Feedback model',
        properties: llmProperties(256),
      },
      {
        id: 24,
        type: 'output/output',
        pos: [2200, 820],
        size: [210, 80],
        flags: {},
        order: 17,
        mode: 0,
        inputs: [{ name: '*', type: '*', link: 24 }],
        outputs: [],
        title: 'Feedback output',
        properties: {
          uniqueId: '24',
          type: 'text',
          label: 'Feedback',
          value: '',
        },
        widgets_values: ['Feedback', 'text'],
      },
    ],
    links: [
      [1, 1, 0, 4, 0, 'string'],
      [2, 2, 0, 4, 1, 'string'],
      [3, 3, 0, 5, 0, 'string'],
      [5, 5, 0, 8, 0, 'message'],
      [7, 4, 0, 8, 1, 'string'],
      [8, 8, 0, 9, 0, 'string'],
      [9, 9, 0, 10, 0, 'number'],
      [10, 11, 0, 12, 0, 'string'],
      [12, 12, 0, 15, 0, 'message'],
      [14, 8, 0, 15, 1, 'string'],
      [15, 15, 0, 16, 0, 'string'],
      [16, 16, 0, 17, 0, '[string]'],
      [17, 18, 0, 19, 0, 'string'],
      [18, 4, 0, 20, 0, 'string'],
      [19, 8, 0, 20, 1, 'string'],
      [21, 19, 0, 23, 0, 'message'],
      [23, 20, 0, 23, 1, 'string'],
      [24, 23, 0, 24, 0, 'string'],
    ],
    groups: [
      {
        title: 'Input',
        bounding: [20, 0, 320, 620],
        color: '#3f5159',
        font_size: 24,
      },
      {
        title: 'Assessment',
        bounding: [360, 0, 1180, 400],
        color: '#3f5159',
        font_size: 24,
      },
      {
        title: 'Classification',
        bounding: [1200, 420, 1510, 260],
        color: '#3f5159',
        font_size: 24,
      },
      {
        title: 'Feedback',
        bounding: [1200, 760, 1250, 300],
        color: '#3f5159',
        font_size: 24,
      },
    ],
    config: {},
    extra: {},
    version: 0.4,
  },
};
